# Generated by Django 4.0.3 on 2022-04-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_feed',
            field=models.BooleanField(default=True),
        ),
    ]
