# Generated by Django 4.0.3 on 2024-01-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_show_in_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
